class pageObject {
    signedInUser = ':nth-child(2) > .greet > .logged-in'
    chevronSignedInUser = ':nth-child(2) > .customer-welcome > .customer-name > .action'
    contextMenuMyAccount = ':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a'
    pageBase = '.base'

    //My Account 
    editBtn = '.block-dashboard-info > .block-content > .box > .box-actions > .edit > span'
    firstNameField = '#firstname'
    firstNameFieldError = '#firstname-error'
    lastNameField = '#lastname'
    lastNameFieldError = '#lastname-error'
    saveBtn = '#form-validate > .actions-toolbar > div.primary > .action > span'
    snackBarSuccess = '.message-success'
    snackBarError = '.message-error'
    snackBarSuccessText = '.message-success > div'
    snackBarErrorText = '.message-error > div'
    checkboxChangeEmail = '#change-email'
    emailField = '#email'
    emailError = '#email-error'
    currentPasswordField = '#current-password'
    newPasswordField = '#password'
    passwordConfirmation = '#password-confirmation'
    currentPasswordError = '#current-password-error'
    newPasswordError = '#password-error'
    passwordConfirmationError = '#password-confirmation-error'
    checkboxChangePassword = ':nth-child(7) > .label > span'

    //Address
    manageAddressBtn = '.box-billing-address > .box-actions > .action > span'
    saveAddressBtn = '#form-validate > .actions-toolbar > div.primary > .action > span'
    telephoneField = '#telephone'
    telephoneFieldError = '#telephone-error'
    streetAddressField = '#street_1'
    streetAddressFieldError = '#street_1-error'
    cityField = '#city'
    cityFieldError = '#city-error'
    stateField = '#region_id'
    stateFieldError = '#region_id-error'
    postalCodeField = '#zip'
    postalCodeFieldError = '#zip-error'

    companyField = '#company'
    street2Field = '#street_2'
    street3Field = '#street_3'
    countryField = '#country'
    defaultBillingAddress = '.box-address-billing > .box-content > address'
}
export default pageObject;